#!/usr/bin/awk -f
#
# Fails the commit if commit message has overlong lines.

# Ignore rest of the file containing '--verbose' output.
/^# ------------------------ >8 ------------------------$/ {
	exit(0);
}

# Ignore comments.
/^[ 	]*#/ {
	next;
}

NR == 1 && /.{51}/ {
	print("The first line of the commit message exceeds 50 characters. Aborting.");
	exit(1);
}

NR > 1 && /.{73}/ {
	print("Line " NR " of the commit message exceeds 72 characters. Aborting.");
	exit(1);
}

