#!/bin/sh
#
# Prints a warning if the summary commit message is longer than 50 chars, and
# fails the commit if the message exceeds 72 chars.
#
# If lines in the body of the commit exceed 72 chars then the commit is
# reformatted using `fmt(1)`.
#
# If there is no blank line between the summary message and the body of the
# commit message then the commmit fails.
#
# See: https://github.com/jaf7C7/cfg/tree/main/.config/git/hooks

~/.config/git/hooks/commit-msg "$@"
