#!/bin/sh
#
# Fails the operation if there are formatting errors or failing tests.
#
# See: https://github.com/jaf7C7/cfg/tree/main/.config/git/hooks

~/.config/git/hooks/pre-commit \
	--list-different-cmd='npm run --silent format:list-different' \
	--format-cmd='npm run --silent format'
