/**
 * Returns an array of cell co-ordinates immediately adjacent to the given cell.
 *
 * @param {String} stringCell
 * @returns {String[]}
 */
function neighbours(stringCell) {
    const [x, y] = destringify(stringCell);
    return [
        [x, y + 1],
        [x + 1, y + 1],
        [x + 1, y],
        [x + 1, y - 1],
        [x, y - 1],
        [x - 1, y - 1],
        [x - 1, y],
        [x - 1, y + 1]
    ].map((e) => e.toString());
}

/**
 * Turns a cell string into a cell array.
 *
 * @param {String} stringCell
 * @returns {Number[]}
 */
function destringify(stringCell) {
    return stringCell.split(',').map((e) => Number(e));
}

/**
 * Turns a set of arrays into a set of strings.
 *
 * @param {Set<Number[]>} cells
 * @returns {Set<String>}
 */
function stringifySet(cells) {
    return new Set(Array.from(cells).map((e) => e.toString()));
}

/**
 * Returns a boolean value indicating whether a given cell is present in a set
 * of cells.
 *
 * @param {String} stringCell
 * @param {Set<String>} stringCells
 * @returns Boolean
 */
function contains(stringCell, stringCells) {
    return stringCells.has(stringCell);
}

/**
 * Returns the set of cells which each occur exactly three times in the counter
 * object.
 *
 * @param {Object} counter
 * @returns {Set<String>}
 */
function newStringCells(counter) {
    const result = new Set();
    for (const [stringCell, count] of Object.entries(counter)) {
        if (count === 3) {
            result.add(stringCell);
        }
    }
    return new Set(result);
}

/**
 * Returns a new set with each cell from the original set cast from a string to
 * an array.
 *
 * @param {Set<String>} stringCells
 * @returns {Set<Number[]>}
 */
function destringifySet(stringCells) {
    return new Set(Array.from(stringCells).map((e) => destringify(e)));
}

/**
 * Returns the set of cells generated by applying the rules of the game to an
 * initial set of cells, producing the next "generation" of cells.
 *
 * @param {Set<Number[]>} cells
 * @returns {Set<Number[]>}
 */
export function next(cells) {
    const stringCells = stringifySet(cells);
    let result = new Set();
    const counter = {};

    for (const stringCell of stringCells) {
        let liveNeighbourCount = 0;

        for (const stringNeighbour of neighbours(stringCell)) {
            if (contains(stringNeighbour, stringCells)) {
                liveNeighbourCount += 1;
            } else {
                counter[stringNeighbour] =
                    stringNeighbour in counter
                        ? counter[stringNeighbour] + 1
                        : 1;
            }
        }

        if (liveNeighbourCount > 1) {
            result.add(stringCell);
        }
    }

    for (const newStringCell of newStringCells(counter)) {
        result.add(newStringCell);
    }

    return destringifySet(result);
}
