/**
 * Returns an array of cell co-ordinates immediately adjacent to the given cell.
 *
 * @param {Number[]} cell
 * @returns {Number[]}
 */
function neighbours(cell) {
    const [x, y] = cell;
    return [
        [x, y + 1],
        [x + 1, y + 1],
        [x + 1, y],
        [x + 1, y - 1],
        [x, y - 1],
        [x - 1, y - 1],
        [x - 1, y],
        [x - 1, y + 1]
    ];
}

/**
 * Returns a boolean value indicating whether a given cell is present in a set
 * of cells.
 *
 * @param {Number[]} cell
 * @param {Set<Number[]>} cells
 * @returns Boolean
 */
function contains(cell, cells) {
    for (const c of cells) {
        if (cell[0] === c[0] && cell[1] === c[1]) {
            return true;
        }
    }
    return false;
}

/**
 * Returns the set of cells which each occur exactly three times in the counter
 * object.
 *
 * @param {Object} counter
 * @returns {Set<Number[]>}
 */
function newCells(counter) {
    const result = new Set();
    for (const [cellString, count] of Object.entries(counter)) {
        if (count === 3) {
            const cell = cellString.split(',').map((e) => Number(e));
            result.add(cell);
        }
    }
    return new Set(result);
}

/**
 * Returns the set of cells generated by applying the rules of the game to an
 * initial set of cells, producing the next "generation" of cells.
 *
 * @param {Set<Number[]>} cells
 * @returns {Set<Number[]>}
 */
export function next(cells) {
    let result = new Set();
    const counter = {};

    for (const cell of cells) {
        const liveNeighbours = new Set();

        for (const neighbour of neighbours(cell)) {
            if (contains(neighbour, cells)) {
                liveNeighbours.add(neighbour);
            } else {
                counter[neighbour] =
                    neighbour in counter ? counter[neighbour] + 1 : 1;
            }
        }

        if (liveNeighbours.size > 1) {
            result.add(cell);
        }
    }

    for (const newCell of newCells(counter)) {
        result.add(newCell);
    }

    return result;
}
