import { Cell } from './cell.js';

/**
 * Returns an array of cells immediately adjacent to the given cell.
 *
 * @param {Cell} cell
 * @returns {Cell[]}
 */
function neighbours(cell) {
    const { x, y } = cell;
    return [
        new Cell(x, y + 1),
        new Cell(x + 1, y + 1),
        new Cell(x + 1, y),
        new Cell(x + 1, y - 1),
        new Cell(x, y - 1),
        new Cell(x - 1, y - 1),
        new Cell(x - 1, y),
        new Cell(x - 1, y + 1)
    ];
}

/**
 * Returns the set of cells which will become alive, due to them each having 3
 * live neighbours.
 *
 * @param {{ [key: string]: number }} counter
 * @returns {Set<string>}
 */
function newCells(counter) {
    return new Set(Object.keys(counter).filter((cell) => counter[cell] === 3));
}

/**
 * Returns the set of cells generated by applying the rules of the game to an
 * initial set of cells, producing the next "generation" of cells.
 *
 * @param {Set<string>} cells
 * @returns {Set<string>}
 */
export function next(cells) {
    const result = new Set();
    const counter = {};

    for (const cell of [...cells].map(Cell.fromString)) {
        let liveNeighbourCount = 0;

        for (const neighbour of neighbours(cell)) {
            const key = neighbour.toString();
            if (cells.has(key)) {
                liveNeighbourCount += 1;
            } else {
                counter[key] = key in counter ? counter[key] + 1 : 1;
            }
        }

        if (liveNeighbourCount > 1 && liveNeighbourCount < 4) {
            result.add(cell.toString());
        }
    }

    for (const cell of newCells(counter)) {
        result.add(cell);
    }

    return result;
}
